### ISSUE TITLE
Contact form not submitting

### ISSUE THREAD

**Issue by nanijb** [raspgot/Contact-Form-PHP#12]
On localhost getting error
`{"error":true,"message":["missing-input-response"]}`

on Live 
This page isn’t working right now
xxxxx.co.uk can't currently handle this request.
HTTP ERROR 500

**Comment by raspgot** [comment]
You must to fill domains correctly in recaptcha admin or desactivate the check origin of reCAPTCHA solutions

![image](https://user-images.githubusercontent.com/16710364/234507473-5881bda2-65a1-4da0-8fa8-6656fc9a994b.png)

**Comment by nanijb** [comment]
could you please send the working file to recheck the code.

**Comment by raspgot** [comment]
Do you have value in this input ?
![image](https://user-images.githubusercontent.com/16710364/234525108-0bf788b9-d2cc-4fb5-a837-e476dfaad175.png)

The code is here: https://github.com/raspgot/Contact-Form-PHP/releases/tag/1.3.0

**Comment by nanijb** [comment]
i did not put any value....
is i need to put value in the input tag. if yes where can i get the value.

**Comment by nanijb** [comment]
on Live Its getting token value
<input name="recaptcha-token" type="hidden" value="03AL8dmw8EXueTrUo6xS3tAqPhwBPICH_hwsZCdyaq0eGFME5mqregrRmml4-htYp_-7_Xbotr1SdQ1ZExc1nRzSmUfZenVPhb86Vra84r71rwr3ORvHHqCVkiKNpRu5PhIDRRgPalMvpjWSaUpbhV-ddAGsJJSUqvnhxQ0lNErcejgSDlADMQUinMWSgy064oYYEmf0gEAXaMB0W59Vx1mnp3Pevl_vmLq770X7c8eiZkBqeVikbKIT7BkejSL4WDIC6nMNN0BzJYk3jo0JsM7_CbJbjGQjDGEDaWl9IAsULiNQEL-WCJ4EUa-1RMD0fD2yiE4PWIX4QKgwnU0BMHAkRha4veVv2F0aibCiaJcA_MIuM4JjlLXuAT-B01eTpInN6beyoYiUlo3UMaeOK2OK38oIr1WLdLFQHrF353TV0HNFyWulVBGTzUDQUD92vP4Okz5TFvrHhCJEsv2bT9Ah-tawDHL_7_9DutxXafoefrS0gbrit2pTw7p86Joc8fjANqTcq_w36mU4FGoit_GtGyCU29A9zYX5G_IahZZlNIBMB2N2fQcV7wHeaV0fp8mKiqHN7Yj0QcPA_5yHdGEYUYOEwqSSWBcTwp106s4dCSRvZkpWWAZcqRLG6MEP-CVqYe4oN4WgsbKlqcPtThKi0qlgnxj3poed_3x5ttszG4JmROSMPnPPXovTyad_RQ8-FZ_oT4FVDPrp6vxr8jBgu6lwhp3pQ_tVJ-n_ExfoyvLRycRiPMOg7-WFX5n3Hpi690rOSKaFKpj-lbWQ-1APKE9and-JyldVLtp32urgogojPTwJlhNCwNvXk8TgCcmgD8f2ZU3KhU2VmdS-9Qi4s4Q_6y3i-owTTzhd7KQue0ROY3wsQqdftc9k11iYUR4M4HUcs13XvBpCvfl05USt6koKUjNKgCEYkWnCoPzBjBgIhBKcbaZm31eywhFN1kRRVdm9g7Se1wQUkizwb6Jn6GJT-tGsAzI5x9Dyn0AiuKCTpFACPRq_98FnqCmlT1Hh-EeDb6fS2sqbucnAatg94AaGvKzWTF2AHXE1kg9G_e-bQQSx20OuQQ6oOpIWmApkzNf26UAMr_YMNFuCJwiUGBo09dBTfY4WohS0c5xTv3uaWGNMMC4BpowbsbupTHEqlbRjxmJK0muhv31-uOT5bI2SbFlPJc4LpbbK1D_YA907hCgwKkFk0BtrsrsiO_x4JVz4bDlPStCqHnqJqzmM30agBRKgYPw_VOAegli3rUaozAsQs4E3_08hjv1gB-FJAa4bPPMm7n066lxofzirirRPirotgNbdUmXKGA78COyOGrG9dAysPSPpxmoZWYS6-S62rYYxGMJN8NoHjY7PTK95Ahh7DHjnLlFppqXNMHL53rQdVha1JxmJzRSb6B_NNyyv0kTrGp">

but not getting any success msg

**Comment by raspgot** [comment]
You can try to set `$mail->SMTPDebug  = true;` in AjaxForm.php

**Comment by nanijb** [comment]
fetch('AjaxForm.php', { *Failed to load resource: the server responded with a status of 500 ()

getting this issue...

**Comment by raspgot** [comment]
AjaxForm.php is not in the same directory of index.html, you must to move it or change this: `<form action="AjaxForm.php"`

**Comment by nanijb** [comment]
the file is in the same directory and given path also correct. i dont know how to resolve this issue.

**Comment by raspgot** [comment]
So i dont know, what about PHP/Apache logs ?

**Comment by nanijb** [comment]
success msg is not hetting.

**Comment by raspgot** [comment]
I am not a magician, need more details if you want help

Are u sure you follow these steps ? https://github.com/raspgot/Contact-Form-PHP#configuration

**Comment by nanijb** [comment]
i did all things and now i am getting mail from contact but not getting success msg.

**Comment by raspgot** [comment]
Can you give me the link where the form is hosted?

**Comment by nanijb** [comment]
sahatech.co.uk

**Comment by raspgot** [comment]
You need to set `$mail->SMTPDebug` to `SMTP::DEBUG_OFF` when the code is online 😉

**Comment by nanijb** [comment]
oh i forgotten to change that. thank you for helping me.

**Comment by raspgot** [comment]
No problem, you can give a star if it help you 👍
