### ISSUE TITLE
Uncaught ReferenceError: e is not defined

### ISSUE THREAD

**Issue by madnazz** [raspgot/Contact-Form-PHP#14]
I have an error in the console and when I submit the form I get the error "missing-input-response". I have seen the other posts about this error but could not fix it.

Console Error:

`AjaxForm.js:68 Uncaught ReferenceError: e is not defined
    at checkRecaptcha (AjaxForm.js:68:5)
    at onload (AjaxForm.js:16:5)`

I have checked the keys several times and proceeded as in the instructions.

JS: const reCAPTCHA_site_key
PHP: const SECRET_KEY
HTML: api.js?render=

I have also checked the URL which is also correct, have also created a new website with new keys, unfortunately without success.

I can't get figure out

Here is the form: https://www.nighthub.ch/

Thanks for your help

**Comment by raspgot** [comment]
You can try to pass the event to the `checkRecaptcha` function

:14 `checkRecaptcha(e);`
:50 `checkRecaptcha(e);`
:68 `const checkRecaptcha = (e) => {`

**Comment by madnazz** [comment]
Have tried, but does not work: https://www.nighthub.ch/
