### ISSUE TITLE
SyntaxError: JSON.parse

### ISSUE THREAD

**Issue by Canaletto22** [raspgot/Contact-Form-PHP#15]
I think I settled everything as instructed. The form is able sent and I get an email, but there is a constant error in the console on Chrome and on Mozilla. And because it always an error on JSON, the visitor who sends the form cannot see the successful send message.
With chrome it is the following:
Error encountered: SyntaxError: unexpected token '<',"<br /> < b >"... is not valid JSON

With Mozilla:
Error encountered: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by raspgot** [comment]
You were able to resolve the issue @Canaletto22 ?
