### ISSUE TITLE
Error: HOSTNAME_MISMATCH 

### ISSUE THREAD

**Issue by jessicana** [raspgot/Contact-Form-PHP#4]
**Issue description**
I get the error: <b>hostname-mismatch</b>. I am sure that I have entered the private and public keys correctly as per the instructions. This error is described in the ReCaptcha.php file as highlighted below, but I am not sure what is triggering it.

```
    /**
     * Expected hostname did not match
     * @const string
     */
    const E_HOSTNAME_MISMATCH = 'hostname-mismatch';
```

**Environment**
OS name and version: Windows 10 Pro
PHP version: PHP 8.0.3
Web server name and version: ubuntu 20.04
google/ReCaptcha version: v.3
Browser name and version: Chrome 89.0.4389.90 (Official Build) (64-bit)

<b>How can I solve this error?</b>

**Comment by raspgot** [comment]
Hey,
U use any vhost on your configuration ? You must to be sure about the domain you enter in the recaptcha admin
It's typically an error of mismatch keys.

**Comment by aubreyz** [comment]
I have this same error. I am 100% certain the public key is entered correctly in both places, the private key in one place, and the domain in the recaptcha admin is also correct. Is there here some simple way with the existing code to temporarily switch the recaptcha off.

**Comment by raspgot** [comment]
What's the domain ?

**Comment by aubreyz** [comment]
Thanks for your help @raspgot -- 
Try here - https://www.oboehannah.co.uk/testemailer/
that is the original from you but only modified in three respects
- Secret key entered in one place in code
- Public key entered in 2 places

I have checked and re-checked the data on google and all three codes are definitely correct. 
It is possible I have done something really dumb, but I can't figure it out... so anything you can give is much appreciated. 

On the ReCaptcha console the domain is entered simply as oboehannah.co.uk

Happy to send you the php source (with the password) offline

**Comment by raspgot** [comment]
Maybe try to regenerate new keys ?
Otherwise I'm not sure the ".co.uk" is available: https://developers.google.com/recaptcha/docs/domain_validation

![recaptcha_admin](https://user-images.githubusercontent.com/16710364/209682292-bdba8a5f-6cff-480d-ae36-d35745e45194.PNG)

**Comment by aubreyz** [comment]
Thank you for this. I regenerated the keys (V3), and replaced them in the same three places - (public in index and the js, and private in the php). I think it takes some time for Google to make the changes so I will need to report back:
- immediately afterwards it gives connection-failedhostname-mismatch
- 5 minutes later it now gives missing-input-response (so back to other thread)!

Perhaps in an hour or so it will be back to Hostname_Mismatch

Nothing at all changed other than the three replacement codes

**Comment by aubreyz** [comment]
A further 15 minutes later it is back to HOSTNAME_MISMATCH
![image](https://user-images.githubusercontent.com/25100168/209685762-94fe2605-8ba7-4c6f-9c29-4deaeb9a8514.png)

**Comment by raspgot** [comment]
I think domain extension .co.uk is a problem, try to uncheck this to be fixed

![captcha](https://user-images.githubusercontent.com/16710364/209686748-8ee7a39f-d1c6-44a7-a532-de5229fcd939.PNG)

**Comment by aubreyz** [comment]
Aha....  if I go to https://oboehannah.co.uk/testemailer/ it works!!!
so it seems that google despite working with subdomains does not recognise
https://www.oboehannah.co.uk/testemailer/
and
https://oboehannah.co.uk/testemailer/
as being in the same domain....

So just entering oboehannah.co.uk in the console is not enough!

**Comment by raspgot** [comment]
Yes u need to add both

**Comment by aubreyz** [comment]
Thanks for help, and all your work writing this form

**Comment by raspgot** [comment]
No problem, you can give a star if u like this
