### ISSUE TITLE
Missing Input Response

### ISSUE THREAD

**Issue by sqpp** [raspgot/Contact-Form-PHP#5]
Hello,

I've already set up Site Key, SMTP details, Secret Key and when I've submit the form, I do receive
 ["missing-input-response"]
 
 Additionally, when I try to submit form without Captcha, it still lets me do it.

**Comment by sqpp** [comment]
Sorted out, sorry.

**Comment by reym0n** [comment]
I have this problem too . what i should do ?

**Comment by aubreyz** [comment]
I also have this exact problem. Really unhelpful not to be told how it was solved. The email address field gets no tick with any email and the alert showing this comment just remains....

**Comment by raspgot** [comment]
You must to check if you have any value in this input:
`
<input name="recaptcha-token" type="hidden">`

![dsfsdfsdf](https://user-images.githubusercontent.com/16710364/209642064-f0a3add2-7fc1-4296-b277-2b8636f52b3c.PNG)

**Comment by nanijb** [comment]
> Sorted out, sorry.

hey, i too have the same issue. can you please share me code to solve the issue.
