### ISSUE TITLE
 Uncaught ReferenceError: angular is not defined

### ISSUE THREAD

**Issue by Renda77CZ** [raspgot/Contact-Form-PHP#8]
Hello, my problem send . Click Send, script stop, button name will change to SENDING.... and STOP :(
Console error: 
Uncaught ReferenceError: angular is not defined
    submitHandler https://xxxxxxx/AjaxForm.js:58
    jQuery 7
    submitHandler https://xxxxxxx/AjaxForm.js:56
    jQuery 11
    <anonymous> https://xxxxxxx/AjaxForm.js:14
    jQuery 13
Thank you.

**Comment by raspgot** [comment]
Hello,

This repo doesn't use angular
However an error is encountered on https://robotnicek.cz

`file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0`

To use the ReCaptcha Google library you need to allow `allow_url_fopen` parameter on your server (php.ini)

**Comment by Renda77CZ** [comment]
Php settings parameter allow_url_fopen to ON.
Button name will change to SENDING.... and STOP, no send, no error mesaage?

**Comment by raspgot** [comment]
You have a server error `Error 503 Service Unavailable`, you must check your HTTP  logs

**Comment by Renda77CZ** [comment]
Hi, the problem was "- STARTTLS". I changed the settings to "PHPMailer::ENCRYPTION_SMTPS;", email send.

The problem is still there:
Console error:
Uncaught ReferenceError: angular is not defined
submitHandler https://xxxxxxx/AjaxForm.js:58
jQuery 7
submitHandler https://xxxxxxx/AjaxForm.js:56
jQuery 11
https://xxxxxxx/AjaxForm.js:14
jQuery 13

**Comment by raspgot** [comment]
You call this in AjaxForm.js:58
```javascript
alertShowing(angular.fromJson(response));
```
You must to replace by :
```javascript
alertShowing(JSON.parse(response));
```

**Comment by Renda77CZ** [comment]
Code replace, problem not solved.

 Uncaught SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 5 of the JSON data
    submitHandler https://robotnicek.cz/AjaxForm.js:58
    jQuery 7
    submitHandler https://robotnicek.cz/AjaxForm.js:56
    jQuery 11
    <anonymous> https://robotnicek.cz/AjaxForm.js:14
    jQuery 13
    
   Button name will change to SENDING.... and STOP

**Comment by raspgot** [comment]
Disable verbose debug output `$mail->SMTPDebug  = SMTP::DEBUG_OFF;`
It shoulb be use in local environnement, not in production for security reasons

**Comment by Renda77CZ** [comment]
Yes, yes, yes, perfect, very thank you. All is OK, super.

**Comment by raspgot** [comment]
No problem, you can give a star if it help you 👍
