### ISSUE TITLE
error when cookie is rejected

### ISSUE THREAD

**Issue by ceepackna** [raspgot/Contact-Form-PHP#9]
hello,

I am implementing my cookie notice and everything related. well the case is that when someone rejects the cookies and tries to submit the form I get the error " {"code":"MethodNotAllowed","message":"POST is not allowed"} ".

I know that this error appears because there is no token because the cookies have been blocked. My question is, is there any way that if the cookies have already been rejected the send button is deactivated or, failing that, a message appears saying that there is than accept cookies

**Comment by raspgot** [comment]
Hello,
Do you use a special consent platform system ?

**Comment by ceepackna** [comment]
I use a privacy driver plugin (pdcc). that blocks cookies until the user accepts them and in case of rejecting, leaves them blocked.

**Comment by raspgot** [comment]
First you need to inject reCAPTCHA script dynamically in `index.html`

~~<script defer src="https://www.google.com/recaptcha/api.js?render=GOOGLE_PUBLIC_KEY"></script>~~
```html
<script>
    var yourGdprCookie = true|false;
    if (yourGdprCookie) {
        var script = document.createElement('script');
        script.src = 'https://www.google.com/recaptcha/api.js?render=GOOGLE_PUBLIC_KEY'
        document.body.appendChild(script);
    }
</script>
```

Method for retrieve cookie: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/get

Then in `AjaxForm.js` you must do the same verification and disable submit button

```javascript
$(function () {
    var yourGdprCookie = true|false;
    if (yourGdprCookie) {
        //code
    } else {
        $("#submit-btn").prop("disabled", true);
        $("#submit-btn").text("Cookie not allowed");
    }
});
```

**Comment by ceepackna** [comment]
Thanks, I'll try to implement it :)
